export const PRIZE_STRUCTURES = {
    "Bhagyathara": {
      first: "₹1 Crore",
      consolation: "₹5,000",
      second: "₹30 Lakh",
      third: "₹5 Lakh",
      fourth: "₹5,000",
      fifth: "₹2,000",
      sixth: "₹1,000",
      seventh: "₹500",
      eighth: "₹200",
      ninth: "₹100",
    },
  
    "Sthree Sakthi": {
      first: "₹1 Crore",
      consolation: "₹5,000",
      second: "₹30 Lakh",
      third: "₹5 Lakh",
      fourth: "₹5,000",
      fifth: "₹2,000",
      sixth: "₹1,000",
      seventh: "₹500",
      eighth: "₹200",
      ninth: "₹100",
    },
  
    "Dhanalekshmi": {
      first: "₹1 Crore",
      consolation: "₹5,000",
      second: "₹30 Lakh",
      third: "₹5 Lakh",
      fourth: "₹5,000",
      fifth: "₹2,000",
      sixth: "₹1,000",
      seventh: "₹500",
      eighth: "₹200",
      ninth: "₹100",
    },
  
    "Karunya Plus": {
      first: "₹1 Crore",
      consolation: "₹5,000",
      second: "₹30 Lakh",
      third: "₹5 Lakh",
      fourth: "₹5,000",
      fifth: "₹2,000",
      sixth: "₹1,000",
      seventh: "₹500",
      eighth: "₹200",
      ninth: "₹100",
    },
  
    "Suvarna Keralam": {
      first: "₹1 Crore",
      consolation: "₹5,000",
      second: "₹30 Lakh",
      third: "₹5 Lakh",
      fourth: "₹5,000",
      fifth: "₹2,000",
      sixth: "₹1,000",
      seventh: "₹500",
      eighth: "₹200",
      ninth: "₹100",
    },
  
    "Karunya": {
      first: "₹1 Crore",
      consolation: "₹5,000",
      second: "₹25 Lakh",
      third: "₹10 Lakh",
      fourth: "₹5,000",
      fifth: "₹2,000",
      sixth: "₹1,000",
      seventh: "₹500",
      eighth: "₹200",
      ninth: "₹100",
    },
  
    "Samrudhi": {
      first: "₹1 Crore",
      consolation: "₹5,000",
      second: "₹30 Lakh",
      third: "₹5 Lakh",
      fourth: "₹5,000",
      fifth: "₹2,000",
      sixth: "₹1,000",
      seventh: "₹500",
      eighth: "₹200",
      ninth: "₹100",
    },
  
    "Summer Bumper": {
      first: "₹10 Crore",
      consolation: "₹1 Lakh",
      second: "₹10 Lakh",
      third: "₹5 Lakh",
      fourth: "₹1 Lakh",
      fifth: "₹5,000",
      sixth: "₹2,000",
      seventh: "₹1,000",
      eighth: "₹500",
      ninth: "₹250",
    },
  
    "Vishu Bumper": {
      first: "₹10 Crore",
      consolation: "₹1 Lakh",
      second: "₹10 Lakh",
      third: "₹5 Lakh",
      fourth: "₹1 Lakh",
      fifth: "₹5,000",
      sixth: "₹2,000",
      seventh: "₹1,000",
      eighth: "₹500",
      ninth: "₹250",
    },
  
    "Monsoon Bumper": {
      first: "₹10 Crore",
      consolation: "₹1 Lakh",
      second: "₹10 Lakh",
      third: "₹5 Lakh",
      fourth: "₹1 Lakh",
      fifth: "₹5,000",
      sixth: "₹2,000",
      seventh: "₹1,000",
      eighth: "₹500",
      ninth: "₹250",
    },
  
    "Onam Bumper": {
      first: "₹10 Crore",
      consolation: "₹1 Lakh",
      second: "₹10 Lakh",
      third: "₹5 Lakh",
      fourth: "₹1 Lakh",
      fifth: "₹5,000",
      sixth: "₹2,000",
      seventh: "₹1,000",
      eighth: "₹500",
      ninth: "₹250",
    },
  
    "Pooja Bumper": {
      first: "₹10 Crore",
      consolation: "₹1 Lakh",
      second: "₹10 Lakh",
      third: "₹5 Lakh",
      fourth: "₹1 Lakh",
      fifth: "₹5,000",
      sixth: "₹2,000",
      seventh: "₹1,000",
      eighth: "₹500",
      ninth: "₹250",
    },
  
    "Christmas Bumper": {
      first: "₹10 Crore",
      consolation: "₹1 Lakh",
      second: "₹10 Lakh",
      third: "₹5 Lakh",
      fourth: "₹1 Lakh",
      fifth: "₹5,000",
      sixth: "₹2,000",
      seventh: "₹1,000",
      eighth: "₹500",
      ninth: "₹250",
    },
  } as const;